---
title: "HW 8"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidymodels)

#had an issue when I first ran it, this came from the ? in some of the titles. I just removed those and now it seems to read in fine!
SeoulBikeData <- read_csv("SeoulBikeData.csv")
#changint to a tibble to make things easier
seoul_tbl<-as.tibble(SeoulBikeData)


```

##EDA

#Checking the Data

```{r}
#First we will check to see if there is anything missing

#In or to figure out which data is numerical and categorical, we first look at the structure of the Seoul Bike Data CsV
str(seoul_tbl)

#now that we have the structure, we will find summary stats for numeric columns 

seoul_tbl |>
  summarize(across(c(`Rented Bike Count`, `Temperature(C)`,  `Humidity(%)`, `Wind speed (m/s)`,`Visibility (10m)`, `Dew point temperature(C)`, `Solar Radiation (MJ/m2)`, `Rainfall(mm)`,  `Snowfall (cm)`), 
                   list(min=min, median=median, mean = mean, sd = sd, max=max), 
                   .names = "{col}_{fn}"))

#now we will figure out what unique names there are in the categorical variable columns by doing counts

seoul_tbl|>
  count(Date)
seoul_tbl |>
  count(Seasons)
seoul_tbl |>
  count(Holiday)
seoul_tbl |>
  count(`Functioning Day`)
seoul_tbl |>
  count(Hour)


#So now we know: 
#There are many different dates.
#Seasons are Autumn, Winter, Spring, Summer
#Holiday options are Holiday or No Holiday.
#Functioning Day options are No or Yes

#now let's convert that date column to an actual date using lubridate

seoul_tbl$Date <- dmy(seoul_tbl$Date)

#double check that the structure changed like we wanted it to

str(seoul_tbl$Date)

#It did!

#Now we want to turn our character variables into factors
colnames(seoul_tbl)

#this will get the unique values to help turn the variables into factors
unique(seoul_tbl$Seasons)

unique(seoul_tbl$Holiday)

unique(seoul_tbl$`Functioning Day`)


unique(seoul_tbl$Hour)


seoul_tbl<-seoul_tbl|>
  mutate(Seasons = as.factor(Seasons),
         Holiday=as.factor(Holiday),
        Hour=as.factor(Hour),
         `Functioning Day`=as.factor(`Functioning Day`)
  ) 
#quick check to make sure converting to factors worked as desired
str(seoul_tbl)

#Looks like it works now!

#renaming all the columns to easier things
seoul_tbl<- seoul_tbl|>
  rename("bike_rentals"="Rented Bike Count", "hour"="Hour", "temp"="Temperature(C)", "humidity"= "Humidity(%)", "wind"="Wind speed (m/s)","visibility"="Visibility (10m)", "dew_temp"="Dew point temperature(C)", "solar_rad"="Solar Radiation (MJ/m2)","rainfall"= "Rainfall(mm)", "snowfall"="Snowfall (cm)", "season"="Seasons", "holiday"="Holiday","functioning"="Functioning Day")

#checking if this worked as desired 
colnames(seoul_tbl)
#it worked!

#now we want to explore the data some more, seeing what we notice

#Let's first look at summary statistics for temp
temp_sum<- seoul_tbl|>
  summarize(
    min = min(temp, na.rm = TRUE),
    median = median(temp, na.rm = TRUE),
    mean = mean(temp, na.rm = TRUE),
    sd = sd(temp, na.rm = TRUE),
    max = max(temp, na.rm = TRUE)
  )
print(temp_sum)

#Let's look at summary statistics for humidity
humidity_sum<- seoul_tbl|>
  summarize(
    min = min(humidity, na.rm = TRUE),
    median = median(humidity, na.rm = TRUE),
    mean = mean(humidity, na.rm = TRUE),
    sd = sd(humidity, na.rm = TRUE),
    max = max(humidity, na.rm = TRUE)
  )
print(humidity_sum)

#Let's look at summary statistics for wind
wind_sum<- seoul_tbl|>
  summarize(
    min = min(wind, na.rm = TRUE),
    median = median(wind, na.rm = TRUE),
    mean = mean(wind, na.rm = TRUE),
    sd = sd(wind, na.rm = TRUE),
    max = max(wind, na.rm = TRUE)
  )
print(wind_sum)

#Let's look at summary statistics for visibility
visibility_sum<- seoul_tbl|>
  summarize(
    min = min(visibility, na.rm = TRUE),
    median = median(visibility, na.rm = TRUE),
    mean = mean(visibility, na.rm = TRUE),
    sd = sd(visibility, na.rm = TRUE),
    max = max(visibility, na.rm = TRUE)
  )
print(visibility_sum)

#Let's look at summary statistics for dew temp
dew_temp_sum<- seoul_tbl|>
  summarize(
    min = min(dew_temp, na.rm = TRUE),
    median = median(dew_temp, na.rm = TRUE),
    mean = mean(dew_temp, na.rm = TRUE),
    sd = sd(dew_temp, na.rm = TRUE),
    max = max(dew_temp, na.rm = TRUE)
  )
print(dew_temp_sum)

#Let's look at summary statistics for solar radiation
solar_rad_sum<- seoul_tbl|>
  summarize(
    min = min(solar_rad, na.rm = TRUE),
    median = median(solar_rad, na.rm = TRUE),
    mean = mean(solar_rad, na.rm = TRUE),
    sd = sd(solar_rad, na.rm = TRUE),
    max = max(solar_rad, na.rm = TRUE)
  )
print(solar_rad_sum)

#Let's look at summary statistics for rainfall
rainfall_sum<- seoul_tbl|>
  summarize(
    min = min(rainfall, na.rm = TRUE),
    median = median(rainfall, na.rm = TRUE),
    mean = mean(rainfall, na.rm = TRUE),
    sd = sd(rainfall, na.rm = TRUE),
    max = max(rainfall, na.rm = TRUE)
  )
print(rainfall_sum)

#Let's look at summary statistics for snowfall
snowfall_sum<- seoul_tbl|>
  summarize(
    min = min(snowfall, na.rm = TRUE),
    median = median(snowfall, na.rm = TRUE),
    mean = mean(snowfall, na.rm = TRUE),
    sd = sd(snowfall, na.rm = TRUE),
    max = max(snowfall, na.rm = TRUE)
  )
print(snowfall_sum)

#now let's do the same for bike rentals, really focusing on what we notice

bike_sum<- seoul_tbl|>
  summarize(
    min = min(bike_rentals, na.rm = TRUE),
    median = median(bike_rentals, na.rm = TRUE),
    mean = mean(bike_rentals, na.rm = TRUE),
    sd = sd(bike_rentals, na.rm = TRUE),
    max = max(bike_rentals, na.rm = TRUE)
  )
print(bike_sum)


#now lets do some analyis while also grouping with bike rentals to see if we see anything that we should remove from the data
seoul_tbl |>
  group_by(functioning)|>
  summarize(across(c( bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))
 
#I am noticing here that when the functioning is "no" there are no bike rentals!

seoul_tbl |>
  group_by(functioning, season)|>
  summarize(across(c( bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))

#Here I am noticing that the only time there was no functioning was in autumn and spring

seoul_tbl |>
  group_by(hour)|>
  summarize(across(c( bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))


seoul_tbl |>
  group_by(holiday)|>
  summarize(across(c( bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))


#If we care about bike rentals, it makes sense to remove the days there was no functioning.

seoul_tbl|>
filter(functioning=="Yes")

print(seoul_tbl)

seoul_tbl<-seoul_tbl |>
  group_by(Date,season,holiday)|>
summarize(
day_bike_rentals=sum(bike_rentals),
day_rainfall=sum(rainfall),
day_snowfall=sum(snowfall),
day_temp=mean(temp),
day_humidity=mean(humidity),
day_wind=mean(wind),
day_visibility=mean(visibility),
day_dew_temp=mean(dew_temp),
day_solar_rad=mean(solar_rad)
)

#Now let's do the same summary statistics but for this new subsetted data


#Let's first look at summary statistics for temp
new_temp_sum<- seoul_tbl|>
  summarize(
    min = min(day_temp, na.rm = TRUE),
    median = median(day_temp, na.rm = TRUE),
    mean = mean(day_temp, na.rm = TRUE),
    sd = sd(day_temp, na.rm = TRUE),
    max = max(day_temp, na.rm = TRUE)
  )
print(new_temp_sum)

#Let's look at summary statistics for humidity
new_humidity_sum<- seoul_tbl|>
  summarize(
    min = min(day_humidity, na.rm = TRUE),
    median = median(day_humidity, na.rm = TRUE),
    mean = mean(day_humidity, na.rm = TRUE),
    sd = sd(day_humidity, na.rm = TRUE),
    max = max(day_humidity, na.rm = TRUE)
  )
print(new_humidity_sum)

#Let's look at summary statistics for wind
new_wind_sum<- seoul_tbl|>
  summarize(
    min = min(day_wind, na.rm = TRUE),
    median = median(day_wind, na.rm = TRUE),
    mean = mean(day_wind, na.rm = TRUE),
    sd = sd(day_wind, na.rm = TRUE),
    max = max(day_wind, na.rm = TRUE)
  )
print(new_wind_sum)

#Let's look at summary statistics for visibility
new_visibility_sum<- seoul_tbl|>
  summarize(
    min = min(day_visibility, na.rm = TRUE),
    median = median(day_visibility, na.rm = TRUE),
    mean = mean(day_visibility, na.rm = TRUE),
    sd = sd(day_visibility, na.rm = TRUE),
    max = max(day_visibility, na.rm = TRUE)
  )
print(new_visibility_sum)

#Let's look at summary statistics for dew temp
new_dew_temp_sum<- seoul_tbl|>
  summarize(
    min = min(day_dew_temp, na.rm = TRUE),
    median = median(day_dew_temp, na.rm = TRUE),
    mean = mean(day_dew_temp, na.rm = TRUE),
    sd = sd(day_dew_temp, na.rm = TRUE),
    max = max(day_dew_temp, na.rm = TRUE)
  )
print(new_dew_temp_sum)

#Let's look at summary statistics for solar radiation
new_solar_rad_sum<- seoul_tbl|>
  summarize(
    min = min(day_solar_rad, na.rm = TRUE),
    median = median(day_solar_rad, na.rm = TRUE),
    mean = mean(day_solar_rad, na.rm = TRUE),
    sd = sd(day_solar_rad, na.rm = TRUE),
    max = max(day_solar_rad, na.rm = TRUE)
  )
print(new_solar_rad_sum)

#Let's look at summary statistics for rainfall
new_rainfall_sum<- seoul_tbl|>
  summarize(
    min = min(day_rainfall, na.rm = TRUE),
    median = median(day_rainfall, na.rm = TRUE),
    mean = mean(day_rainfall, na.rm = TRUE),
    sd = sd(day_rainfall, na.rm = TRUE),
    max = max(day_rainfall, na.rm = TRUE)
  )
print(new_rainfall_sum)

#Let's look at summary statistics for snowfall
new_snowfall_sum<- seoul_tbl|>
  summarize(
    min = min(day_snowfall, na.rm = TRUE),
    median = median(day_snowfall, na.rm = TRUE),
    mean = mean(day_snowfall, na.rm = TRUE),
    sd = sd(day_snowfall, na.rm = TRUE),
    max = max(day_snowfall, na.rm = TRUE)
  )
print(new_snowfall_sum)

#now let's do the same for bike rentals, really focusing on what we notice

new_bike_sum<- seoul_tbl|>
  summarize(
    min = min(day_bike_rentals, na.rm = TRUE),
    median = median(day_bike_rentals, na.rm = TRUE),
    mean = mean(day_bike_rentals, na.rm = TRUE),
    sd = sd(day_bike_rentals, na.rm = TRUE),
    max = max(day_bike_rentals, na.rm = TRUE)
  )
print(bike_sum)

#now lets do some analyis while also grouping with bike rentals to see if we see anything that we should remove from the data

seoul_tbl |>
  summarize(across(c(day_bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))
 
#I am noticing here that when the functioning is "no" there are no bike rentals!

seoul_tbl |>
  group_by(season)|>
  summarize(across(c(day_bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))

#Here I am noticing that the only time there was no functioning was in autumn and spring

seoul_tbl |>
  group_by(holiday)|>
  summarize(across(c(day_bike_rentals), 
                   list("max"=max,"min"=min, "mean" = mean, "median" = median, "sd"=sd), 
                   .names = "{.fn}_{.col}"))


#here we look at the bike rentals over the year, you can see it is much lower in the winter
ggplot(seoul_tbl, aes(x = Date, y = day_bike_rentals)) +
  geom_line(color = "steelblue") +
  labs(
    title = "Daily Bike Rentals Over the Year",
    x = "Date",
    y = "Number of Bike Rentals"
  ) +
  theme_minimal()

#here is the same plot but with different colors for each season
ggplot(seoul_tbl, aes(x = Date, y = day_bike_rentals, color = season)) +
  geom_line() +
  labs(
    title = "Daily Bike Rentals Over the Year by Season",
    x = "Date",
    y = "Number of Bike Rentals"
  ) +
  theme_minimal()


#here we look at the snow fall over the year, you can see it is much higher in the winter, no snow in summer months in seoul
ggplot(seoul_tbl, aes(x = Date, y = day_snowfall)) +
  geom_line(color = "steelblue") +
  labs(
    title = "Snowfall",
    x = "Date",
    y = "Snowfall"
  ) +
  theme_minimal()


#here is is a plot for with different colors for each season, it looks like the high days of rain are in summer with least rain in winter
ggplot(seoul_tbl, aes(x = Date, y = day_rainfall, color = season)) +
  geom_line() +
  labs(
    title = "Rainfall Over the Year by Season",
    x = "Date",
    y = "Rainfall"
  ) +
  theme_minimal()

#average bike rentals by season as a boxplot, highest median rentals in summer which makes sense
ggplot(seoul_tbl, aes(x = season, y = day_bike_rentals)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Bike Rentals by Season", x = "Season", y = "Bike Rentals")

#average bike rentals by holiday as a boxplot, higher median of rentals when there was no holiday
ggplot(seoul_tbl, aes(x = holiday, y = day_bike_rentals)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Bike Rentals by holiday", x = "holiday", y = "Bike Rentals")


#weather effects on bike rentals with some smoothing. Higher temps had more rentals
ggplot(seoul_tbl, aes(x = day_temp, y = day_bike_rentals)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "Bike Rentals vs Temperature", x = "Temperature (C)", y = "Bike Rentals")


#now lets find all of the correlations

colnames(seoul_tbl)

numeric_data <- seoul_tbl |>
  ungroup() |>
  select(day_bike_rentals, day_dew_temp, day_humidity, day_wind, day_rainfall, day_snowfall, day_solar_rad, day_visibility, day_temp)

cor_matrix <- cor(numeric_data, use = "complete.obs")
print(cor_matrix)

#trying to plot some faceted scatter plots with bike rentals and other numeric variables

# Reshape numeric variables into long format
numeric_long <- seoul_tbl |>
  ungroup()|>
  select(day_bike_rentals, day_dew_temp, day_humidity, day_wind, day_rainfall, day_snowfall, day_solar_rad, day_visibility, day_temp)|>
  pivot_longer(cols = -day_bike_rentals,
               names_to = "variable",
               values_to = "value")

# Plot using facets
ggplot(numeric_long, aes(x = value, y = day_bike_rentals)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~variable, scales = "free_x") +
  labs(x = "Value", y = "Bike Rentals") +
  theme_minimal()


# Reshape numeric variables into long format
numeric_long <- seoul_tbl |>
  ungroup()|>
  select(day_bike_rentals, day_dew_temp, day_humidity, day_wind, day_rainfall, day_snowfall, day_solar_rad, day_visibility, day_temp)|>
  pivot_longer(cols = -day_bike_rentals,
               names_to = "variable",
               values_to = "value")




```

#Split the Data

```{r}
library(rsample)
#Use functions from tidymodels to split the data into a training and test set (75/25 split). Use the strata argument to stratify the split on the seasons variable.
set.seed(10)
seoul_split <- initial_split(seoul_tbl, prop = 0.75, strata = season)
seoul_train <- training(seoul_split)
seoul_test <- testing(seoul_split)
seoul_train

seoul_test 
#On the training set, create a 10 fold CV split
folds <- rsample::vfold_cv(seoul_train, v = 10, strata = season)
```

##Fitting MLR Models

#1st recipe

```{r}
first_rec<-
recipe(day_bike_rentals ~ ., data = seoul_tbl) |>
  #creating a week day weeend factor
 step_mutate(
    day_type = factor(if_else(wday(ymd(Date), label = TRUE) %in% c("Sat", "Sun"), "Weekend", "Weekday"))
  ) |>
  step_rm(Date)|>
#normaizing the numeric
step_normalize(all_numeric())|>
  step_dummy(season, holiday, day_type) 


first_prep <- prep(first_rec)
first_data <-bake(first_prep, new_data = NULL)
```

#2nd recipe:

```{r}
second_rec<-
recipe(day_bike_rentals ~ ., data = seoul_tbl) |>
  #creating a week day weeend factor
 step_mutate(
    day_type = factor(if_else(wday(ymd(Date), label = TRUE) %in% c("Sat", "Sun"), "Weekend", "Weekday"))
  ) |>
  step_rm(Date)|>
#normaizing the numeric
  step_dummy(season, holiday, day_type) |>
  #addng in interaction
 step_interact(terms = ~ starts_with("season_") *  starts_with("holiday_")) |>
  step_interact(terms = ~ starts_with("season_") * day_temp)|>
  step_interact(terms = ~ day_temp * day_rainfall)|>
  step_normalize(all_numeric())


second_prep <- prep(second_rec)
second_data <-bake(second_prep, new_data = NULL)
```
#3rd recipe:

```{r}
third_rec<-
recipe(day_bike_rentals ~ ., data = seoul_tbl) |>
  #creating a week day weeend factor
 step_mutate(
    day_type = factor(if_else(wday(ymd(Date), label = TRUE) %in% c("Sat", "Sun"), "Weekend", "Weekday"))
  ) |>
  step_rm(Date)|>
#normaizing the numeric
  step_dummy(season, holiday, day_type) |>
  #addng in interaction
 step_interact(terms = ~ starts_with("season_") *  starts_with("holiday_")) |>
  step_interact(terms = ~ starts_with("season_") * day_temp)|>
  step_interact(terms = ~ day_temp * day_rainfall)|>
  step_normalize(all_numeric())|>

  
#adding in the quadratics
step_poly(all_numeric_predictors(), degree = 2, options = list(raw = TRUE))


third_prep <- prep(third_rec)
third_data <-bake(third_prep, new_data = NULL)
```


#setting up models

```{r}
#Now set up our linear model fit to use the “lm” engine.
#for first one
first_mod<-linear_reg() %>%
 set_engine("lm") %>%
 translate()
 
 first_wfl <- workflow() |>
 add_recipe(first_rec) |>
 add_model(first_mod)

 #do the resamples with the cv
 cv_results <- fit_resamples(
  first_wfl,
  resamples =folds,
  metrics = metric_set(rmse)
)
 collect_metrics(cv_results)

first_fit <- first_wfl |>
 fit(seoul_train)
first_fit |>
 tidy()

#for second one
sec_mod<-linear_reg() %>%
 set_engine("lm") %>%
 translate()
 
sec_wfl <- workflow() |>
 add_recipe(second_rec) |>
 add_model(sec_mod)

 #do the resamples with the cv
 sec_cv_results <- fit_resamples(
 sec_wfl,
  resamples =folds,
  metrics = metric_set(rmse)
)
 collect_metrics(sec_cv_results)

sec_fit <- sec_wfl |>
 fit(seoul_train)
sec_fit |>
 tidy()


#for third one
third_mod<-linear_reg() %>%
 set_engine("lm") %>%
 translate()
 
third_wfl <- workflow() |>
 add_recipe(third_rec) |>
 add_model(third_mod)

 #do the resamples with the cv
 third_cv_results <- fit_resamples(
 third_wfl,
  resamples =folds,
  metrics = metric_set(rmse)
)
 collect_metrics(third_cv_results)

third_fit <- third_wfl |>
 fit(seoul_train)
sec_fit |>
 tidy()

```
Second model appears best since it has the lowest mean RSME so we will use that for the final model!

```{r}
best_fit <- last_fit(sec_wfl, split = seoul_split, metrics = metric_set(rmse))

collect_metrics(best_fit)

collect_predictions(best_fit)

final_model <- extract_fit_parsnip(best_fit$.workflow[[1]])

tidy(final_model)

tidy(best_fit)
```